settings:
  title: 'Status Page'
  url: 'https://status.returnearly.net' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 30 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: zonewatcher-com
    name: ZoneWatcher
    description: 'The ZoneWatcher Application'
    url: 'https://zonewatcher.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: returnearly-net
    name: Return Early
    description: 'The Return Early Website'
    url: 'https://returnearly.net'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
